name: Validate JSON

on:
  push:
    paths:
      - '**.json'
  pull_request:
    paths:
      - '**.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Validator
        run: npm install -g ajv-cli

      - name: Validate JSON Files
        run: |
          ajv validate -s docs/schema.json -d known.json
          ajv validate -s docs/schema.json -d patched.json

      - name: Check Metadata Updates
        run: |
          node .github/scripts/check-metadata.js
